### ISSUE TITLE
Abstürzten des CRI-DemoClient

### ISSUE THREAD

**Issue by Maxi2nuss** [CommonplaceRobotics/CRI-DemoClient#4]
Moin, und zwar habe ich folgendes Problem. 
Mein CRI-DemoClient bricht dauernd ab und ich kann ehrlicherweise nicht genau sagen wieso. 
Ich bekomme den Fehler system.stackoverflowexeption nach einiger Zeit raus. 
Kann mir in diesem Thema jemand vielleicht helfen? 

Mit freundlichen Grüßen 

Maxi

**Comment by cpr-mab** [comment]
Hallo Maxi,

benutzt du irgendwelche Funktionen des Democlients bevor der Fehler auftritt, bzw. tritt es auch auf wenn du den Democlient einfach nur verbindest und dann wartest? Wie lange dauert es etwa bis der Fehler auftritt?

Mit freundlichen Grüßen,
Markus

**Comment by Maxi2nuss** [comment]
Moin Markus, 

danke für deine Rückmeldung. 

Das Problem besteht auch, wenn ich nur den Democlient laufen lasse. Anfangs läuft das Programm ohne Probleme nur nach ungefähr 5 Minuten stürzt es ab. Also nicht das Programm selber sondern das Interface. 
Ich steuere mit dem Programm mein IGUS Roboter, dieser erkennt mittels QR-Code welchen Auftrag er ausführen soll. Die Unterprogramm der einzelnen Aufträge sind in IGUS. Ich sende nur einen Befehl an die IGUS Steuerung welchen Auftrag diese ausführen soll, mehr nicht. Ich hoffe ich habe es verständlich erklärt. 

Ich habe mal mein Interface und meinen Code von der MessageBox reingestellt. Ich habe selbst erstmal versucht das Problem zu lösen, aber ohne Erfolg. 
Ich kann auch nicht ganz nachvollziehen, wieso meine MessageBox so überfüllt ist. Kann ich das nicht minimieren? 
Die andere Frage ist, was bringen mir diese ausgaben in der MessageBox? 

Ich hoffe ich habe es verständlich erklärt, falls nicht sag bescheid. 

Mit freundlichen Grüßen 

Maxi
![Code1TextboxMessage](https://github.com/CommonplaceRobotics/CRI-DemoClient/assets/138516714/fe973907-7db8-4ece-bcbd-16298ef723f7)
![TextBoxMessage](https://github.com/CommonplaceRobotics/CRI-DemoClient/assets/138516714/2579d48d-b25a-4bd4-9d77-8272e6e5e3f1)
![TextBoxMessageBetrieb](https://github.com/CommonplaceRobotics/CRI-DemoClient/assets/138516714/91606c41-1ed8-4c92-9871-9f675de99702)

**Comment by Maxi2nuss** [comment]
Entschuldige um Struktur im Anhang zu bekommen: 
1 Bild: Mein veränderter Programmcode 
2 Bild: Interface 
3 Bild: Interface in Betrieb, einfaches durchlaufen des Programmes

**Comment by Maxi2nuss** [comment]
Moin Markus, 

konnte das Problem soweit beheben. Hab bisschen probiert getestet und am Ende funktionierte es. 
Programm macht was es soll und das Interface stürzt auch nicht ab. 

Danke dir Markus, hast mir schon allein mit der Nachricht die Motivation gegeben das Problem zu lösen. 
Gottes Segen. 

Mit freundlichen Grüßen, 
Maxi

**Comment by cpr-mab** [comment]
Danke für die Rückmeldung und gut dass es jetzt läuft. Falls der Fehler am Democlient liegt sag gerne bescheid, dann kann ich versuchen es zu beheben.

Das Feld mit den Log-Nachrichten zeigt welche CRI-Nachrichten übertragen werden oder ob Fehler aufgetreten sind. Das ist gelegentlich zum Testen nützlich oder um zu verstehen wie das CRI funktioniert.
